#include "opts.h"

int EMGUI_LCD_WIDTH = 320;
int EMGUI_LCD_HEIGHT = 240;
int EMGUI_STATUS_BAR_HEIGHT = 26;
int EMGUI_MODAL_DLG_BTN_SPACING = 100;
int EMGUI_WINDOW_HEADER_LENGTH = 25;

int EMGUI_LABEL_MAX_LENGTH = 1000;
int EMGUI_DEBUG = 0;

// GUI COLORS

// RGB565 definition 
int EMGUI_COLOR_SEA_5 = 0x02AC;	// Sea colors map from drakest to lightest
int EMGUI_COLOR_SEA_4 = 0x1B2E;
int EMGUI_COLOR_SEA_3 = 0x0413;
int EMGUI_COLOR_SEA_2 = 0x3599;
int EMGUI_COLOR_SEA_1 = 0x5DD9;

int EMGUI_COLOR_BROWN_5 = 0xA280;	// Earth colors map from drakest to lightest
int EMGUI_COLOR_BROWN_4 = 0xBBA5;
int EMGUI_COLOR_BROWN_3 = 0xFBC0;
int EMGUI_COLOR_BROWN_2 = 0xFCC7;
int EMGUI_COLOR_BROWN_1 = 0xFDAD;

int EMGUI_COLOR_WHITE	= 0xFFFF;
int EMGUI_COLOR_GRAY	= 0xC618;
int EMGUI_COLOR_BLACK	= 0;

int EMGUI_COLOR_RED     = 0xF800;
int EMGUI_COLOR_GREEN   = 0x7E0;
int EMGUI_COLOR_BLUE    = 0x1F;


// STATUSBAR STORY
int EMGUI_COLOR_MENU_HEADER_TEXT = 0;
int EMGUI_COLOR_STATUS_BAR_BG = 0xFFFF;

int EMGUI_COLOR_MESSAGE_TEXT = 0;
int EMGUI_MENU_BUTTON_LABEL_TEXT_COLOR = 0;
int EMGUI_MENU_BUTTON_LABEL_BG_COLOR = 0xFFFF;

// PLOT Colors
int EMGUI_COLOR_PLOT_BACKGROUND = 0xFFFF;
int EMGUI_COLOR_PLOT_GRIDS = 0x5DD9;
int EMGUI_COLOR_PLOT_SCALE_MARKER = 0xA280;

